#include <xc.h>
#include <sys/attribs.h>
#include "buzzer.h"

/*
 * Variables interne
 */

static u16 notes[] = {
    BUZZER_NOTE_C1, BUZZER_NOTE_CS1, BUZZER_NOTE_D1, BUZZER_NOTE_DS1, BUZZER_NOTE_E1, BUZZER_NOTE_F1, BUZZER_NOTE_FS1, BUZZER_NOTE_G1, BUZZER_NOTE_GS1, BUZZER_NOTE_A1, BUZZER_NOTE_AS1, BUZZER_NOTE_B1,
    BUZZER_NOTE_C2, BUZZER_NOTE_CS2, BUZZER_NOTE_D2, BUZZER_NOTE_DS2, BUZZER_NOTE_E2, BUZZER_NOTE_F2, BUZZER_NOTE_FS2, BUZZER_NOTE_G2, BUZZER_NOTE_GS2, BUZZER_NOTE_A2, BUZZER_NOTE_AS2, BUZZER_NOTE_B2,
    BUZZER_NOTE_C3, BUZZER_NOTE_CS3, BUZZER_NOTE_D3, BUZZER_NOTE_DS3, BUZZER_NOTE_E3, BUZZER_NOTE_F3, BUZZER_NOTE_FS3, BUZZER_NOTE_G3, BUZZER_NOTE_GS3, BUZZER_NOTE_A3, BUZZER_NOTE_AS3, BUZZER_NOTE_B3,
    BUZZER_NOTE_C4, BUZZER_NOTE_CS4, BUZZER_NOTE_D4, BUZZER_NOTE_DS4, BUZZER_NOTE_E4, BUZZER_NOTE_F4, BUZZER_NOTE_FS4, BUZZER_NOTE_G4, BUZZER_NOTE_GS4, BUZZER_NOTE_A4, BUZZER_NOTE_AS4, BUZZER_NOTE_B4,
    BUZZER_NOTE_C5, BUZZER_NOTE_CS5, BUZZER_NOTE_D5, BUZZER_NOTE_DS5, BUZZER_NOTE_E5, BUZZER_NOTE_F5, BUZZER_NOTE_FS5, BUZZER_NOTE_G5, BUZZER_NOTE_GS5, BUZZER_NOTE_A5, BUZZER_NOTE_AS5, BUZZER_NOTE_B5,
    BUZZER_NOTE_C6, BUZZER_NOTE_CS6, BUZZER_NOTE_D6, BUZZER_NOTE_DS6, BUZZER_NOTE_E6, BUZZER_NOTE_F6, BUZZER_NOTE_FS6, BUZZER_NOTE_G6, BUZZER_NOTE_GS6, BUZZER_NOTE_A6, BUZZER_NOTE_AS6, BUZZER_NOTE_B6,
    BUZZER_NOTE_C7, BUZZER_NOTE_CS7, BUZZER_NOTE_D7, BUZZER_NOTE_DS7, BUZZER_NOTE_E7, BUZZER_NOTE_F7, BUZZER_NOTE_FS7, BUZZER_NOTE_G7, BUZZER_NOTE_GS7, BUZZER_NOTE_A7, BUZZER_NOTE_AS7, BUZZER_NOTE_B7,
    BUZZER_NOTE_C8, BUZZER_NOTE_CS8, BUZZER_NOTE_D8, BUZZER_NOTE_DS8, BUZZER_NOTE_E8, BUZZER_NOTE_F8, BUZZER_NOTE_FS8, BUZZER_NOTE_G8, BUZZER_NOTE_GS8, BUZZER_NOTE_A8, BUZZER_NOTE_AS8, BUZZER_NOTE_B8
};

/*
 * Interruption
 */

__ISR(_TIMER_2_VECTOR, IPL6AUTO) BuzzerTimer()
{
    LATAbits.LATA4 = !LATAbits.LATA4;
    IFS0bits.T2IF = 0;
}


void buzzer_init()
{
    // Initialisation de la pin du buzzer
    LATAbits.LATA4 = 0;
    TRISAbits.TRISA4 = 0;

    // Initialisation du timer
    IEC0bits.T2IE = 1;
    IPC2bits.T2IP = 6;
    IFS0bits.T2IF = 0;

    T2CON = 0;
    //T2CONbits.TCS = 0; // Clock PBCLK
    T2CONbits.TCKPS = 0; // Timer Prescal 1:1 (500000 = 0.5s)
    T2CONbits.TGATE = 0;
    T2CONbits.ON = 0;
}

void buzzer_play(u8 note)
{
    T2CONbits.ON = 0;
    IFS0bits.T2IF = 0;

    PR2 = BUZZER_PERIOD / notes[note];
    TMR2 = 0;

    T2CONbits.ON = 1;
}

void buzzer_stop()
{
    LATAbits.LATA4 = 0;
    T2CONbits.ON = 0;
    TMR2 = 0;
}
